package com.yiran.xingtian.web.mapper;

import com.yiran.xingtian.common.model.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_user_0
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_user_0
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_user_0
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_user_0
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_user_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zd_user_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    /************************************** User defined apis ************************************/
    /**
     *
     * @param uid
     * @return
     */
    User findByUid(@Param("uid") Long uid);

    /**
     *
     * @param beginUid
     * @param endUid
     * @return
     */
    List<User> findAllByUidRange(@Param("beginUid") Long beginUid, @Param("endUid") Long endUid);

    /**
     *
     * @param uids
     * @return
     */
    int updateUsersUids(@Param("list") List<Long> uids);

    int updateUsersBatch(@Param("users") List<User> users);

}